apiVersion: v1
kind: Service
metadata:
  name: customerservice
spec:
  type: NodePort
  selector:
    app: customerservice
  ports:
    - protocol: TCP
      nodePort: 30742
      port: 9742
      targetPort: 9742
