apiVersion: v1
kind: Service
metadata:
  name: menuservice
spec:
  type: NodePort
  selector:
    app: menuservice
  ports:
    - protocol: TCP
      nodePort: 30741
      port: 9741
      targetPort: 9741
